version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./html:/var/www/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  php:
    image: php:fpm
    container_name: lemp_php
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    environment:
      - DB_NAME=lemp_bdd
      - TABLE_PREFIX=lemp_
      - DB_HOST=lemp
      - DB_PASSWORD=password
  db:
    image: mariadb
    container_name: lemp_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
