version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./html:/var/www/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
  php:
    build:
      context: ./php-fpm
    container_name: lemp_php
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - nginx
    environment:
      - DB_NAME=lemp_bdd
      - TABLE_PREFIX=lemp_
      - DB_HOST=lemp
      - DB_PASSWORD=password
    ports:
      - 9000:9000
  db:
    image: mariadb
    container_name: lemp_mariadb
    restart: always
    ports:
        - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin
    depends_on:
      - nginx
      - php
      - db
    ports: 
      - 8080:80